#basic
spring.application.name=UnderHear-backend
spring.threads.virtual.enabled=true

#file upload
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB
server.tomcat.max-swallow-size=210MB

#mysql
spring.datasource.url=jdbc:mysql://115.190.254.60:3306/underhear
spring.datasource.username=root
spring.datasource.password=112233ss
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

#Redis
spring.data.redis.host=115.190.254.60
spring.data.redis.port=6379
spring.data.redis.password=112233ss
spring.data.redis.database=0
spring.data.redis.timeout=5s

#mybatis
#配置下划线转驼峰
mybatis.configuration.map-underscore-to-camel-case=true

#GitHub oauth
github.oauth.client-id=Ov23lion0fl6wJ6FP1nR
github.oauth.client-secret=d844b43d94053085dbfb2fc17862beb80eeeb2db
github.oauth.redirect-uri=http://localhost:5173/auth/login

#Gitee oauth
gitee.oauth.client-id=4f73d371755a0ee38614abe64cb5c0e8313f747866b1ff085cb1e6be2078a27b
gitee.oauth.client-secret=8c381300e29c7f714454ff39bd17401b120152d0daf9927264423db0c6e11035
gitee.oauth.redirect-uri=http://localhost:5173/auth/login

#JWT
security.jwt.secret=chuangqianmingyueguangyishidishangshuang
security.jwt.expire-seconds=604800
