spring.application.name=UnderHear-backend

# 数据库编码
spring.datasource.url=jdbc:mysql://47.96.177.210:3306/underhear
spring.datasource.username=root
spring.datasource.password=112233ss
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
